# Generated by Django 3.0.6 on 2020-08-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('approve', 'Can approve comment.'), ('discard', 'Can discard comment.')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('publish', 'Can publish post.'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
    ]
